### ISSUE TITLE
v4 ANR Android

### ISSUE THREAD

**Issue by 345ml** [zyslife/react-native-head-tab-view#96]
## Describe the bug
I'm trying Version 4, but I'm getting this error on Android.

```
io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 5000 ms.
    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:656)
    at android.os.Handler.enqueueMessage(Handler.java:759)
    at android.os.Handler.sendMessageAtTime(Handler.java:708)
    at android.os.Handler.sendMessageDelayed(Handler.java:678)
    at android.os.Handler.post(Handler.java:407)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:66)
    at com.facebook.react.bridge.ReactContext.runOnUiQueueThread(ReactContext.java:333)
    at com.swmansion.reanimated.Scheduler.scheduleOnUI(Scheduler.java:37)
    at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java)
    at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
    at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
    at android.os.Handler.handleCallback(Handler.java:888)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```
## Package versions  
```
"react-native-head-tab-view": "^4.0.0-rc.8",
"react-native-tab-view": "^3.0.1",
"react-native-tab-view-collapsible-header": "^2.0.1",
"react-native-reanimated": "^2.1.0",
```

**Comment by zyslife** [comment]
@345ml Thanks, i got it.
